### ISSUE TITLE
Serial has happened a problem,why?

### ISSUE THREAD

**Issue by ericyhx** [jodersky/akka-serial#45]
when I use you dependecy,
I want to connect Serial port：COM2 to read and write;
I use java like this:

        final ActorSystem system = ActorSystem.create("serial");
        final ActorRef watcher = system.actorOf(Props.create(SerialWatch.class), "watcher");
        final Enumeration.Value parity = Parity.None();
        SerialSettings ss=new SerialSettings(38400,8,false,parity);
        final Serial.Open port = new Serial.Open("COM2", ss, 320);
        final ActorRef serialActor = Serial.get(system).manager();
        serialActor.tell(port,watcher);

and then have exception:
Uncaught error from thread [serial-akka.actor.default-dispatcher-2]: null, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[serial]
java.lang.ExceptionInInitializerError: null
	at akka.serial.sync.SerialConnection$.open(SerialConnection.scala:132)
	at akka.serial.SerialManager$$anonfun$receive$1.$anonfun$applyOrElse$1(SerialManager.scala:27)
	at scala.util.Try$.apply(Try.scala:209)
	at akka.serial.SerialManager$$anonfun$receive$1.applyOrElse(SerialManager.scala:27)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.serial.SerialManager.aroundReceive(SerialManager.scala:13)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: Error running `uname` command
	at scala.sys.package$.error(package.scala:27)
	at akka.serial.sync.UnsafeSerial$.liftedTree1$1(UnsafeSerial.scala:20)
	at akka.serial.sync.UnsafeSerial$.loadPackaged$1(UnsafeSerial.scala:20)
	at akka.serial.sync.UnsafeSerial$.load$1(UnsafeSerial.scala:20)
	at akka.serial.sync.UnsafeSerial$.<init>(UnsafeSerial.scala:20)
	at akka.serial.sync.UnsafeSerial$.<clinit>(UnsafeSerial.scala)
	... 16 common frames omitted

**Comment by jodersky** [comment]
It looks like you're trying to run akka-serial on Windows, which is not supported. See [the list of supported platforms here](http://www.jodersky.ch/akka-serial/downloads/).
